### ISSUE TITLE
Duvidas API Itau

### ISSUE THREAD

**Issue by edilsonsp** [thiagohenrique0810/Atari#1]
Thiago bom dia,

Essa API esta funcionando no padrão Cnab240??

Ela não gera o arquivo né apenas transmite diretamente ao banco?

Outra duvida olhando o exemplo de teste aonde gero essas chaves?

'itau_chave' 	=> '9a6a013b-werf-49a5-bf99-f674761f5775',
'client_id'		=> 'JeRNHwe_jqrwer',
'client_secret'	=> '_CS1YIgcTt0YmETQKM277UsXZ97CUrBf6t6siSCB20000rx-Yi2tvuFDfHn3vMTWv26V_JaSuUuZuYv8lw0a7g2'

**Comment by thiagohenrique0810** [comment]
Isso ela está no padrão CNAB240, ela é uma API que facilita a comunicação com o servidor do Itaú com a sua app em php.
essa chave você deve entrar em contato com o itau para que eles forneçam esses dados

**Comment by pedroantonellini** [comment]
Thiago, tudo certo ? A documentação da API esta bem confusa então gostaria de tirar uma dúvida com você. Você sabe informar se é possivel verificar se o boleto foi pagou ou não via API? Na documentação diz que o tipo_registro = 3 porém não sei se é verídica esta informação.

**Comment by thiagohenrique0810** [comment]
> Thiago, tudo certo ? A documentação da API esta bem confusa então gostaria de tirar uma dúvida com você. Você sabe informar se é possivel verificar se o boleto foi pagou ou não via API? Na documentação diz que o tipo_registro = 3 porém não sei se é verídica esta informação.

**Comment by thiagohenrique0810** [comment]
sim funciona, porem precisa verificar se o itau liberou essa funcionalidade para você, pois funciona como um arquivo de retorno
